loki:
  serviceName: "loki.m2h60.k8s.gauss.eu-west-1.aws.gigantic.io"  # Defaults to "${RELEASE}-loki" if not set
  servicePort: 443
  serviceScheme: https
  user: loki
  password: my-brother-is-thor

external_labels:
  installation: gorilla
  cluster: loki0

rbac:
  create: true
  pspEnabled: true

config:
  client:
    tenant_id: 1

backoff_config:
  max_period: 10m

extraScrapeConfigs:
  - job_name: systemd_journal
    journal:
      json: true
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'systemd_unit'
