loki:
  serviceName: "loki.m2h60.k8s.gauss.eu-west-1.aws.gigantic.io"  # Defaults to "${RELEASE}-loki" if not set
  servicePort: 443
  serviceScheme: https
  user: loki
  password: my-brother-is-thor

rbac:
  create: true
  pspEnabled: true

config:
  client:
    tenant_id: 1


