rbac:
  create: true
  pspEnabled: true

config:
  lokiAddress: "https://loki:my-brother-is-thor@loki.m2h60.k8s.gauss.eu-west-1.aws.gigantic.io/loki/api/v1/push"
  serverPort: null

extra_client_configs:
  tenant_id: 1

  backoff_config:
    max_period: 10m

  external_labels:
    installation: gorilla
    cluster: loki0

extra_scrape_configs:
  - job_name: systemd_journal
    journal:
      json: true
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'systemd_unit'
