checks:
  addAllBuiltIn: true
  exclude:
  - "no-liveness-probe"
  - "required-annotation-email"
  - "required-label-owner"
  - "run-as-non-root"
  - "unset-cpu-requirements"
  - "unset-memory-requirements"
  - "writable-host-mount"
