apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: 2.1.0
version: 3.3.0
home: https://grafana.com/loki
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
- https://github.com/grafana/helm-charts/
- https://github.com/giantswarm/grafana-helm-charts-upstream
- https://github.com/giantswarm/promtail-app
upstreamChartURL: https://github.com/grafana/helm-charts/
maintainers:
- name: Loki Maintainers
  email: lokiproject@googlegroups.com
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/loki-app
- name: unguiculus
engine: gotpl
restrictions:
  namespaceSingleton: true
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
annotations:
  application.giantswarm.io/team: "halo"
