apiVersion: "v1"
name: promtail
version: 2.2.0
appVersion: v2.1.0
kubeVersion: "^1.10.0-0"
description: "Responsible for gathering logs and sending them to Loki"
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
sources:
- https://github.com/grafana/loki
- https://github.com/grafana/helm-charts/
- https://github.com/giantswarm/grafana-helm-charts-upstream
- https://github.com/giantswarm/promtail-app
upstreamChartURL: https://github.com/grafana/helm-charts/
maintainers:
- name: Loki Maintainers
  email: lokiproject@googlegroups.com
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/loki-app
engine: gotpl
restrictions:
  clusterSingleton: true
