apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: 2.5.0
version: 0.4.1
home: https://github.com/giantswarm/promtail-app
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
  - https://github.com/giantswarm/grafana-helm-charts-upstream
upstreamChartURL: https://github.com/grafana/helm-charts
upstreamChartVersion: 6.0.2
icon: https://s.giantswarm.io/app-icons/grafana-loki/2/dark.svg
maintainers:
  - name: Loki Maintainers
    email: lokiproject@googlegroups.com
  - name: unguiculus
  - name: Giant Swarm applications team
    url: https://github.com/giantswarm/loki-app
engine: gotpl
restrictions:
  namespaceSingleton: true
annotations:
  application.giantswarm.io/team: atlas
