apiVersion: v2
name: promtail
description: An agent which ships logs to a Loki instance
type: application
appVersion: 2.2.1
version: 3.6.0
home: https://github.com/giantswarm/promtail-app
sources:
- https://github.com/grafana/loki
- https://github.com/grafana/helm-charts
- https://github.com/giantswarm/grafana-helm-charts-upstream
upstreamChartURL: https://github.com/grafana/helm-charts
upstreamChartVersion: 3.6.0
maintainers:
- name: Loki Maintainers
  email: lokiproject@googlegroups.com
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/loki-app
- name: unguiculus
engine: gotpl
restrictions:
  namespaceSingleton: true
icon: https://s.giantswarm.io/app-icons/grafana-loki/1/light.png
annotations:
  application.giantswarm.io/team: halo
