apiVersion: v2
name: promtail
description: Promtail is an agent which ships the contents of local logs to a Loki instance
type: application
appVersion: 2.5.0
version: 1.0.1
home: https://github.com/giantswarm/promtail-app
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
  - https://github.com/giantswarm/grafana-helm-charts-upstream
  - https://github.com/grafana/helm-charts/tree/main/charts/promtail
icon: https://s.giantswarm.io/app-icons/loki-stack/1/dark.svg
dependencies:
  - name: promtail
    version: 6.8.2
    repository: https://grafana.github.io/helm-charts
maintainers:
  - name: giantswarm/team-atlas
    email: team-atlas@giantswarm.io
engine: gotpl
restrictions:
  namespaceSingleton: true
annotations:
  application.giantswarm.io/team: atlas
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/grafana-loki/2/dark.svg
