# -- Headless service section. Will be deleted when using serviceMonitor
giantswarm:
  labelMonitoring:
    enabled: true
    name: promtail-giantswarm-monitoring
    serviceLabels: {}

promtail:
  rbac:
    # -- Specifies whether a PodSecurityPolicy is to be created
    pspEnabled: true

  image:
    # -- The Docker registry
    registry: docker.io
    # -- Docker image repository
    repository: giantswarm/promtail
    # -- Overrides the image tag whose default is the chart's appVersion
    tag: null
    # -- Docker image pull policy
    pullPolicy: IfNotPresent

  # -- Resource requests and limits
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
