# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

ciliumNetworkPolicy:
  # Must be disabled for imported EKS clusters without cilium as main CNI.
  enabled: true

promtail:
  daemonset:
    autoscaling:
      enabled: true
      # -- We set minAllowed=Requests to help VPA work efficiently
      controlledResources:
      - memory
      minAllowed:
        memory: 128Mi

  rbac:
    # -- Specifies whether a PodSecurityPolicy is to be created
    pspEnabled: true

  networkPolicy:
    enabled: false
    k8sApi:
      port: 443
      cidrs:
        - 0.0.0.0/0

  serviceMonitor:
    enabled: true
    interval: "60s"
    scrapeTimeout: "45s"

  image:
    # -- The Docker registry
    registry: gsoci.azurecr.io
    # -- Docker image repository
    repository: giantswarm/promtail
    # -- Overrides the image tag whose default is the chart's appVersion
    tag: null
    # -- Docker image pull policy
    pullPolicy: IfNotPresent

  # -- Resource requests and limits
  resources:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 128Mi
