{{ if not .Values.promtail.networkPolicy.enabled }}
{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "promtail.selectorLabels" . | nindent 6 }}
  ingress:
    - toPorts:
      - ports:
        - port: "3101"
          protocol: TCP
  egress:
    - toEntities:
        - kube-apiserver
        - world
    - toEndpoints:
      - matchLabels:
          k8s-app: coredns
      - matchLabels:
          k8s-app: k8s-dns-node-cache
      toPorts:
      - ports:
        - port: "53"
          protocol: ANY
        - port: "1053"
          protocol: ANY
        rules:
          dns:
          - matchPattern: '*'
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: loki
      toPorts:
      - ports:
        - port: "80"
          protocol: ANY
        - port: "9095"
          protocol: ANY
{{- end }}
{{- end }}
