{{- if not .Values.promtail.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "promtail.selectorLabels" . | nindent 8 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  selector:
    {{- include "promtail.selectorLabels" $ | nindent 4 }}
  clusterIP: "None"
  ports:
    - protocol: TCP
      port: 9091
      targetPort: {{ .Values.promtail.config.serverPort }}
{{- end }}
