apiVersion: v1
kind: Service
metadata:
  name: {{ include "promtail.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "promtail.selectorLabels" . | nindent 8 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  selector:
    {{- include "promtail.selectorLabels" $ | nindent 4 }}
  clusterIP: "None"
  ports:
    - protocol: TCP
      port: 9091
      targetPort: {{ .Values.config.serverPort }}
